name: illuminative
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  chat_bubbles: ^1.2.0
  cloud_firestore: ^3.1.15
  cupertino_icons: ^1.0.2
  firebase_core: ^1.17.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
